PythonDjangoDemo/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('music.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^register/$', views.UserFormView.as_view(), name='register'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),
    url(r'album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),
    url(r'album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),
]

music/models.py
from django.db import models
from django.urls import reverse


class Album(models.Model):
    title = models.CharField(max_length=512)
    artist = models.CharField(max_length=255)
    genre = models.CharField(max_length=128)
    logo = models.FileField()

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return "Album(" \
               "title='" + self.title + "', " +\
               "artist='" + self.artist + "', " +\
               "genre='" + self.genre + "', " +\
               "logo='" + self.logo + "'" +\
               ")"


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    title = models.CharField(max_length=512)
    type = models.CharField(max_length=16)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return "Song("\
               "title='" + self.title + "', " +\
               "type='" + self.type + "', " +\
               "is_favorite=" + str(self.is_favorite) + ", " +\
               "album='" + self.album.title + "'" +\
               ")"

music/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

music/views.py
from django.contrib.auth import authenticate, login
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.views import generic
from django.views.generic import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .forms import UserForm
from .models import Album


class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'albums'

    def get_queryset(self):
        return Album.objects.all()


class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'


class AlbumCreate(CreateView):
    model = Album
    fields = ['title', 'artist', 'genre', 'logo']


class AlbumUpdate(UpdateView):
    model = Album
    fields = ['title', 'artist', 'genre', 'logo']


class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')


class UserFormView(View):
    form_class = UserForm
    template_name = 'music/registration_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('music:index')

        return render(request, self.template_name, {'form': form})

music/templates/music/album_form.html
{% extends 'music/header.html' %}

{% block title %} PythonDjandoDemo : Add New Album {% endblock %}
{% block albumbs_active %} active {% endblock %}

{% block body %}

    {#index body start#}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 coll-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3>Add New Album</h3>
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'music/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {#index body start#}

{% endblock %}

music/templates/music/detail.html
{% extends 'music/header.html' %}

{% block title %}PythonDjandoDemo: Album - {{ album.title }} by {{ album.artist }}{% endblock %}
{% load staticfiles %}

{% block body %}

    {#body start#}
{#    <img src="{% static 'music/images/' %}{{ album.logo }}" alt="{{ album.logo }}">#}
    <img src="{{ album.logo.url }}" alt="{{ album.logo }}">

    <h1>{{ album.title }}</h1>
    <h2>{{ album.artist }}</h2>

    {% for song in album.song_set.all %}
        {{ song.title }}
        {% if song.is_favorite %}
            <img src="http://i.imgur.com/b9b13Rd.png"/>
        {% endif %}
        <br>
    {% endfor %}

    {#body close#}

{% endblock %}

music/templates/music/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

music/templates/music/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}PythonDjandoDemo{% endblock %}</title>
    {#load static files start#}

    {% load staticfiles %}

    {#css start#}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/css/music.css' %}"/>
    {#css close#}

    {#js start#}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    {#js close#}

    {#load static files close#}
</head>
<body>

    {#navbar start#}
    <nav class="navbar navbar-default">
        <div class="container-fluid">

            {#logo start#}
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'music:index' %}">RohanNewSite</a>
            </div>
            {#logo close#}

            {#items start#}
            <div class="collapse navbar-collapse" id="topNavBar">

                {#albums & songs start#}
                <ul class="nav navbar-nav">
                    <li class="{% block albums_active %}{% endblock %}">
                        <a href="{% url 'music:index' %}">
                            <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums
                        </a>
                    </li>
                     <li class="">
                        <a href="{% url 'music:album-add' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                        </a>
                    </li>
                </ul>
                {#albums & songs close#}

                {#right-side start#}
                <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                        </a>
                    </li>
                </ul>
                {#right-side close#}
            </div>
        </div>
    </nav>
    {#navbar close#}

    {#block start#}
    {% block body %}
        {#body goes here#}
    {% endblock %}
    {#block close#}

</body>
</html>

music/templates/music/index.html
{% extends 'music/header.html' %}

{% block title %} Welcome PythonDjandoDemo {% endblock %}
{% block albums_active %}active{% endblock %}
{% load staticfiles %}

{% block body %}
    {#body start#}
    <div class="albums-container container-fluid">
        <!-- Albums -->
        <div class="row">
{#            <div class="col-sm-12">#}
{#                <h3>{{ user.username }}'s Albums</h3>#}
{#            </div>#}
            {% if albums %}
                {% for album in albums %}
                    <div class="col-sm-4 col-lg-2">
                        <div class="thumbnail">
                            <a href="{% url 'music:detail' album.id %}">
{#                                <img src="{% static 'music/images/' %}{{ album.logo }}" class="img-responsive">#}
                                <img src="{{ album.logo.url }}" class="img-responsive">
                            </a>
                            <div class="caption">
                                <h2>{{ album.album_title }}</h2>
                                <h4>{{ album.artist }}</h4>

                                <!-- View Details -->
                                <a href="{% url 'music:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                                <!-- Delete Album -->
                                <form action="{% url 'music:album-delete' album.id %}" method="post" style="display: inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="album_id" value="{{ album.id }}" />
                                    <button type="submit" class="btn btn-default btn-sm">
                                        <span class="glyphicon glyphicon-trash"></span>
                                    </button>
                                </form>

                                <!-- Favorite Album -->
                                {% comment %}<a href="{% url 'music:favorite_album' album.id %}" class="btn btn-default btn-sm btn-favorite" role="button">
                                    <span class="glyphicon glyphicon-star {% if album.is_favorite %}active{% endif %}"></span>
                                </a>{% endcomment %}

                            </div>
                        </div>
                    </div>
                    {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
                {% endfor %}
            {% else %}
                <div class="col-sm-12">
                    <br>
                    <a href="{% url 'music:album-add' %}">
                        <button type="button" class="btn btn-success">
                            <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Album
                        </button>
                    </a>
                </div>
            {% endif %}
        </div>
    </div>
    {#body close#}
{% endblock %}

music/templates/music/registration_form.html
{% extends 'music/header.html' %}

{% block title %} PythonDjandoDemo : Create a New Account {% endblock %}

{% block body %}

    {#index body start#}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 coll-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3>Create a New Account</h3>
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'music/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {#index body start#}

{% endblock %}